Organizations:

  - &OrdererOrg

      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/meditrack.com/msp

      AdminPrincipal: Role.MEMBER


  - &mayer

      Name: mayer

      ID: mayerMSP

      MSPDir: crypto-config/peerOrganizations/mayer.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.mayer.meditrack.com
          Port: 7051
      

  - &aimko

      Name: aimko

      ID: aimkoMSP

      MSPDir: crypto-config/peerOrganizations/aimko.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.aimko.meditrack.com
          Port: 7051

  - &baia

      Name: baia

      ID: baiaMSP

      MSPDir: crypto-config/peerOrganizations/baia.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.baia.meditrack.com
          Port: 7051

  - &bigrow

      Name: bigrow

      ID: bigrowMSP

      MSPDir: crypto-config/peerOrganizations/bigrow.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.bigrow.meditrack.com
          Port: 7051

  - &dedx

      Name: dedx

      ID: dedxMSP

      MSPDir: crypto-config/peerOrganizations/dedx.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.dedx.meditrack.com
          Port: 7051

  - &btdc

      Name: btdc

      ID: btdcMSP

      MSPDir: crypto-config/peerOrganizations/btdc.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.btdc.meditrack.com
          Port: 7051

  - &abollo

      Name: abollo

      ID: abolloMSP

      MSPDir: crypto-config/peerOrganizations/abollo.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.abollo.meditrack.com
          Port: 7051

  - &fare

      Name: fare

      ID: fareMSP

      MSPDir: crypto-config/peerOrganizations/fare.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.fare.meditrack.com
          Port: 7051

  - &cdsco

      Name: cdsco

      ID: cdscoMSP

      MSPDir: crypto-config/peerOrganizations/cdsco.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.cdsco.meditrack.com
          Port: 7051

  - &cibrc

      Name: cibrc

      ID: cibrcMSP

      MSPDir: crypto-config/peerOrganizations/cibrc.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.cibrc.meditrack.com
          Port: 7051

Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer.meditrack.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Kafka:
    Brokers:
      - kafka0:9092
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092

  Organizations:

Capabilities:
  Channel: &ChannelCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: false
    V1_1: false

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
    Capabilities:
        <<: *ChannelCapabilities

Application: &ApplicationDefaults

  Organizations:

Profiles:

  ProfileTest:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ComposerConsortium:
        Organizations:
          - *mayer
          - *aimko
          - *baia
          - *bigrow
          - *dedx
          - *btdc
          - *abollo
          - *fare
          - *cdsco
          - *cibrc
      agritrackConsortium:
        Organizations:
          - *mayer
          - *aimko
          - *bigrow
          - *btdc
          - *fare
          - *cibrc
      meditrackConsortium:
        Organizations:
          - *mayer
          - *baia
          - *dedx
          - *abollo
          - *cdsco

  ChannelTest:
    <<: *ChannelDefaults
    Consortium: ComposerConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *mayer
          - *aimko
          - *baia
          - *bigrow
          - *dedx
          - *btdc
          - *abollo
          - *fare
          - *cdsco
          - *cibrc
      Capabilities:
          <<: *ApplicationCapabilities
  agritrackChannel:
    Consortium: agritrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *mayer
          - *aimko
          - *bigrow
          - *btdc
          - *fare
          - *cibrc
      Capabilities:
          <<: *ApplicationCapabilities
    
  meditrackChannel:
    <<: *ChannelDefaults
    Consortium: meditrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *mayer
          - *baia
          - *dedx
          - *abollo
          - *cdsco
      Capabilities:
          <<: *ApplicationCapabilities