#/*
# *     _____________  ___  
#      / ___/ ___/ _ \/ _ \ 
#     (__  ) /  /  __/  __/ 
#    /____/_/   \___/\___  
# * File Created: Tuesday, 23rd July 2019 11:13:05 am
# * Author: SreeTeja06 (sreeteja.muthyala@gmail.com)
#
# * There are two ways to write error-free programs; only the third one works.
# * And remeber it is not a bug, it is an undocumented feature
# */
Organizations:

  - &OrdererOrg

      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

  - &mayer

      Name: mayer

      ID: mayerMSP

      MSPDir: crypto-config/peerOrganizations/mayer.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('mayerMSP.admin', 'mayerMSP.peer', 'mayerMSP.client', 'mayerMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('mayerMSP.admin', 'mayerMSP.client', 'mayerMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('mayerMSP.admin', 'mayerMSP.member')"

      AnchorPeers:

        - Host: peer0.mayer.meditrack.com
          Port: 7051
      

  - &aimko

      Name: aimko

      ID: aimkoMSP

      MSPDir: crypto-config/peerOrganizations/aimko.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('aimkoMSP.admin', 'aimkoMSP.peer', 'aimkoMSP.client', 'aimkoMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('aimkoMSP.admin', 'aimkoMSP.client', 'aimkoMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('aimkoMSP.admin', 'aimkoMSP.member')"

      AnchorPeers:

        - Host: peer0.aimko.meditrack.com
          Port: 7051

  - &baia

      Name: baia

      ID: baiaMSP

      MSPDir: crypto-config/peerOrganizations/baia.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('baiaMSP.admin', 'baiaMSP.peer', 'baiaMSP.client', 'baiaMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('baiaMSP.admin', 'baiaMSP.client', 'baiaMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('baiaMSP.admin', 'baiaMSP.member')"

      AnchorPeers:

        - Host: peer0.baia.meditrack.com
          Port: 7051

  - &bigrow

      Name: bigrow

      ID: bigrowMSP

      MSPDir: crypto-config/peerOrganizations/bigrow.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('bigrowMSP.admin', 'bigrowMSP.peer', 'bigrowMSP.client', 'bigrowMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('bigrowMSP.admin', 'bigrowMSP.client', 'bigrowMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('bigrowMSP.admin', 'bigrowMSP.member')"

      AnchorPeers:

        - Host: peer0.bigrow.meditrack.com
          Port: 7051

  - &dedx

      Name: dedx

      ID: dedxMSP

      MSPDir: crypto-config/peerOrganizations/dedx.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('dedxMSP.admin', 'dedxMSP.peer', 'dedxMSP.client', 'dedxMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('dedxMSP.admin', 'dedxMSP.client', 'dedxMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('dedxMSP.admin', 'dedxMSP.member')"

      AnchorPeers:

        - Host: peer0.dedx.meditrack.com
          Port: 7051

  - &btdc

      Name: btdc

      ID: btdcMSP

      MSPDir: crypto-config/peerOrganizations/btdc.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('btdcMSP.admin', 'btdcMSP.peer', 'btdcMSP.client', 'btdcMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('btdcMSP.admin', 'btdcMSP.client', 'btdcMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('btdcMSP.admin', 'btdcMSP.member')"

      AnchorPeers:

        - Host: peer0.btdc.meditrack.com
          Port: 7051

  - &abollo

      Name: abollo

      ID: abolloMSP

      MSPDir: crypto-config/peerOrganizations/abollo.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('abolloMSP.admin', 'abolloMSP.peer', 'abolloMSP.client', 'abolloMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('abolloMSP.admin', 'abolloMSP.client', 'abolloMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('abolloMSP.admin', 'abolloMSP.member')"

      AnchorPeers:

        - Host: peer0.abollo.meditrack.com
          Port: 7051

  - &fare

      Name: fare

      ID: fareMSP

      MSPDir: crypto-config/peerOrganizations/fare.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('fareMSP.admin', 'fareMSP.peer', 'fareMSP.client', 'fareMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('fareMSP.admin', 'fareMSP.client', 'fareMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('fareMSP.admin', 'fareMSP.member')"

      AnchorPeers:

        - Host: peer0.fare.meditrack.com
          Port: 7051

  - &cdsco

      Name: cdsco

      ID: cdscoMSP

      MSPDir: crypto-config/peerOrganizations/cdsco.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('cdscoMSP.admin', 'cdscoMSP.peer', 'cdscoMSP.client', 'cdscoMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('cdscoMSP.admin', 'cdscoMSP.client', 'cdscoMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('cdscoMSP.admin', 'cdscoMSP.member')"

      AnchorPeers:

        - Host: peer0.cdsco.meditrack.com
          Port: 7051

  - &cibrc

      Name: cibrc

      ID: cibrcMSP

      MSPDir: crypto-config/peerOrganizations/cibrc.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('cibrcMSP.admin', 'cibrcMSP.peer', 'cibrcMSP.client', 'cibrcMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('cibrcMSP.admin', 'cibrcMSP.client', 'cibrcMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('cibrcMSP.admin', 'cibrcMSP.member')"

      AnchorPeers:

        - Host: peer0.cibrc.meditrack.com
          Port: 7051

Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer.meditrack.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

  Kafka:
    Brokers:
      - kafka0:9092
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092

  Organizations:

Capabilities:
  Channel: &ChannelCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: false
    V1_1: false

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
    Capabilities:
        <<: *ChannelCapabilities

Application: &ApplicationDefaults

  Organizations:

  Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

Profiles:

  ProfileTest:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ComposerConsortium:
        Organizations:
          - *mayer
          - *aimko
          - *baia
          - *bigrow
          - *dedx
          - *btdc
          - *abollo
          - *fare
          - *cdsco
          - *cibrc
      agritrackConsortium:
        Organizations:
          - *mayer
          - *aimko
          - *bigrow
          - *btdc
          - *fare
          - *cibrc
      meditrackConsortium:
        Organizations:
          - *mayer
          - *baia
          - *dedx
          - *abollo
          - *cdsco

  ChannelTest:
    <<: *ChannelDefaults
    Consortium: ComposerConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *mayer
          - *aimko
          - *baia
          - *bigrow
          - *dedx
          - *btdc
          - *abollo
          - *fare
          - *cdsco
          - *cibrc
      Capabilities:
          <<: *ApplicationCapabilities
  agritrackChannel:
    Consortium: agritrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *mayer
          - *aimko
          - *bigrow
          - *btdc
          - *fare
          - *cibrc
      Capabilities:
          <<: *ApplicationCapabilities
    
  meditrackChannel:
    <<: *ChannelDefaults
    Consortium: meditrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *mayer
          - *baia
          - *dedx
          - *abollo
          - *cdsco
      Capabilities:
          <<: *ApplicationCapabilities