#/*
# *     _____________  ___  
#      / ___/ ___/ _ \/ _ \ 
#     (__  ) /  /  __/  __/ 
#    /____/_/   \___/\___  
# * File Created: Tuesday, 23rd July 2019 11:13:05 am
# * Author: SreeTeja06 (sreeteja.muthyala@gmail.com)
#
# * There are two ways to write error-free programs; only the third one works.
# * And remeber it is not a bug, it is an undocumented feature
# */
Organizations:

  - &OrdererOrg

      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

  - &manuf1

      Name: manuf1

      ID: manuf1MSP

      MSPDir: crypto-config/peerOrganizations/manuf1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('manuf1MSP.admin', 'manuf1MSP.peer', 'manuf1MSP.client', 'manuf1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('manuf1MSP.admin', 'manuf1MSP.client', 'manuf1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('manuf1MSP.admin', 'manuf1MSP.member')"

      AnchorPeers:

        - Host: peer0.manuf1.meditrack.com
          Port: 7051
      

  - &manuf2

      Name: manuf2

      ID: manuf2MSP

      MSPDir: crypto-config/peerOrganizations/manuf2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('manuf2MSP.admin', 'manuf2MSP.peer', 'manuf2MSP.client', 'manuf2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('manuf2MSP.admin', 'manuf2MSP.client', 'manuf2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('manuf2MSP.admin', 'manuf2MSP.member')"

      AnchorPeers:

        - Host: peer0.manuf2.meditrack.com
          Port: 7051

  - &distr1

      Name: distr1

      ID: distr1MSP

      MSPDir: crypto-config/peerOrganizations/distr1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('distr1MSP.admin', 'distr1MSP.peer', 'distr1MSP.client', 'distr1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('distr1MSP.admin', 'distr1MSP.client', 'distr1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('distr1MSP.admin', 'distr1MSP.member')"

      AnchorPeers:

        - Host: peer0.distr1.meditrack.com
          Port: 7051

  - &distr2

      Name: distr2

      ID: distr2MSP

      MSPDir: crypto-config/peerOrganizations/distr2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('distr2MSP.admin', 'distr2MSP.peer', 'distr2MSP.client', 'distr2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('distr2MSP.admin', 'distr2MSP.client', 'distr2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('distr2MSP.admin', 'distr2MSP.member')"

      AnchorPeers:

        - Host: peer0.distr2.meditrack.com
          Port: 7051

  - &logistic1

      Name: logistic1

      ID: logistic1MSP

      MSPDir: crypto-config/peerOrganizations/logistic1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('logistic1MSP.admin', 'logistic1MSP.peer', 'logistic1MSP.client', 'logistic1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('logistic1MSP.admin', 'logistic1MSP.client', 'logistic1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('logistic1MSP.admin', 'logistic1MSP.member')"

      AnchorPeers:

        - Host: peer0.logistic1.meditrack.com
          Port: 7051

  - &logistic2

      Name: logistic2

      ID: logistic2MSP

      MSPDir: crypto-config/peerOrganizations/logistic2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('logistic2MSP.admin', 'logistic2MSP.peer', 'logistic2MSP.client', 'logistic2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('logistic2MSP.admin', 'logistic2MSP.client', 'logistic2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('logistic2MSP.admin', 'logistic2MSP.member')"

      AnchorPeers:

        - Host: peer0.logistic2.meditrack.com
          Port: 7051

  - &pharmacy1

      Name: pharmacy1

      ID: pharmacy1MSP

      MSPDir: crypto-config/peerOrganizations/pharmacy1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('pharmacy1MSP.admin', 'pharmacy1MSP.peer', 'pharmacy1MSP.client', 'pharmacy1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('pharmacy1MSP.admin', 'pharmacy1MSP.client', 'pharmacy1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('pharmacy1MSP.admin', 'pharmacy1MSP.member')"

      AnchorPeers:

        - Host: peer0.pharmacy1.meditrack.com
          Port: 7051

  - &pharmacy2

      Name: pharmacy2

      ID: pharmacy2MSP

      MSPDir: crypto-config/peerOrganizations/pharmacy2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('pharmacy2MSP.admin', 'pharmacy2MSP.peer', 'pharmacy2MSP.client', 'pharmacy2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('pharmacy2MSP.admin', 'pharmacy2MSP.client', 'pharmacy2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('pharmacy2MSP.admin', 'pharmacy2MSP.member')"

      AnchorPeers:

        - Host: peer0.pharmacy2.meditrack.com
          Port: 7051

  - &ia1

      Name: ia1

      ID: ia1MSP

      MSPDir: crypto-config/peerOrganizations/ia1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('ia1MSP.admin', 'ia1MSP.peer', 'ia1MSP.client', 'ia1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ia1MSP.admin', 'ia1MSP.client', 'ia1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ia1MSP.admin', 'ia1MSP.member')"

      AnchorPeers:

        - Host: peer0.ia1.meditrack.com
          Port: 7051

  - &ia2

      Name: ia2

      ID: ia2MSP

      MSPDir: crypto-config/peerOrganizations/ia2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('ia2MSP.admin', 'ia2MSP.peer', 'ia2MSP.client', 'ia2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ia2MSP.admin', 'ia2MSP.client', 'ia2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ia2MSP.admin', 'ia2MSP.member')"

      AnchorPeers:

        - Host: peer0.ia2.meditrack.com
          Port: 7051

Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer.meditrack.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

  Kafka:
    Brokers:
      - kafka0:9092
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092

  Organizations:

Capabilities:
  Channel: &ChannelCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: false
    V1_1: false

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
    Capabilities:
        <<: *ChannelCapabilities

Application: &ApplicationDefaults

  Organizations:

  Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

Profiles:

  ProfileTest:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ComposerConsortium:
        Organizations:
          - *manuf1
          - *manuf2
          - *distr1
          - *distr2
          - *logistic1
          - *logistic2
          - *pharmacy1
          - *pharmacy2
          - *ia1
          - *ia2
      agritrackConsortium:
        Organizations:
          - *manuf1
          - *manuf2
          - *distr2
          - *logistic2
          - *pharmacy2
          - *ia2
      meditrackConsortium:
        Organizations:
          - *manuf1
          - *distr1
          - *logistic1
          - *pharmacy1
          - *ia1

  ChannelTest:
    <<: *ChannelDefaults
    Consortium: ComposerConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *manuf1
          - *manuf2
          - *distr1
          - *distr2
          - *logistic1
          - *logistic2
          - *pharmacy1
          - *pharmacy2
          - *ia1
          - *ia2
      Capabilities:
          <<: *ApplicationCapabilities
  agritrackChannel:
    Consortium: agritrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *manuf1
          - *manuf2
          - *distr2
          - *logistic2
          - *pharmacy2
          - *ia2
      Capabilities:
          <<: *ApplicationCapabilities
    
  meditrackChannel:
    <<: *ChannelDefaults
    Consortium: meditrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *manuf1
          - *distr1
          - *logistic1
          - *pharmacy1
          - *ia1
      Capabilities:
          <<: *ApplicationCapabilities