#/*
# *     _____________  ___  
#      / ___/ ___/ _ \/ _ \ 
#     (__  ) /  /  __/  __/ 
#    /____/_/   \___/\___  
# * File Created: Tuesday, 23rd July 2019 11:13:05 am
# * Author: SreeTeja06 (sreeteja.muthyala@gmail.com)
#
# * There are two ways to write error-free programs; only the third one works.
# * And remeber it is not a bug, it is an undocumented feature
# */
Organizations:

  - &OrdererOrg

      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

  - &manu1

      Name: manu1

      ID: manu1MSP

      MSPDir: crypto-config/peerOrganizations/manu1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('manu1MSP.admin', 'manu1MSP.peer', 'manu1MSP.client', 'manu1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('manu1MSP.admin', 'manu1MSP.client', 'manu1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('manu1MSP.admin', 'manu1MSP.member')"

      AnchorPeers:

        - Host: peer0.manu1.meditrack.com
          Port: 7051
      

  - &manu2

      Name: manu2

      ID: manu2MSP

      MSPDir: crypto-config/peerOrganizations/manu2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('manu2MSP.admin', 'manu2MSP.peer', 'manu2MSP.client', 'manu2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('manu2MSP.admin', 'manu2MSP.client', 'manu2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('manu2MSP.admin', 'manu2MSP.member')"

      AnchorPeers:

        - Host: peer0.manu2.meditrack.com
          Port: 7051

  - &dist1

      Name: dist1

      ID: dist1MSP

      MSPDir: crypto-config/peerOrganizations/dist1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('dist1MSP.admin', 'dist1MSP.peer', 'dist1MSP.client', 'dist1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('dist1MSP.admin', 'dist1MSP.client', 'dist1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('dist1MSP.admin', 'dist1MSP.member')"

      AnchorPeers:

        - Host: peer0.dist1.meditrack.com
          Port: 7051

  - &dist2

      Name: dist2

      ID: dist2MSP

      MSPDir: crypto-config/peerOrganizations/dist2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('dist2MSP.admin', 'dist2MSP.peer', 'dist2MSP.client', 'dist2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('dist2MSP.admin', 'dist2MSP.client', 'dist2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('dist2MSP.admin', 'dist2MSP.member')"

      AnchorPeers:

        - Host: peer0.dist2.meditrack.com
          Port: 7051

  - &logi1

      Name: logi1

      ID: logi1MSP

      MSPDir: crypto-config/peerOrganizations/logi1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('logi1MSP.admin', 'logi1MSP.peer', 'logi1MSP.client', 'logi1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('logi1MSP.admin', 'logi1MSP.client', 'logi1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('logi1MSP.admin', 'logi1MSP.member')"

      AnchorPeers:

        - Host: peer0.logi1.meditrack.com
          Port: 7051

  - &logi2

      Name: logi2

      ID: logi2MSP

      MSPDir: crypto-config/peerOrganizations/logi2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('logi2MSP.admin', 'logi2MSP.peer', 'logi2MSP.client', 'logi2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('logi2MSP.admin', 'logi2MSP.client', 'logi2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('logi2MSP.admin', 'logi2MSP.member')"

      AnchorPeers:

        - Host: peer0.logi2.meditrack.com
          Port: 7051

  - &phar1

      Name: phar1

      ID: phar1MSP

      MSPDir: crypto-config/peerOrganizations/phar1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('phar1MSP.admin', 'phar1MSP.peer', 'phar1MSP.client', 'phar1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('phar1MSP.admin', 'phar1MSP.client', 'phar1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('phar1MSP.admin', 'phar1MSP.member')"

      AnchorPeers:

        - Host: peer0.phar1.meditrack.com
          Port: 7051

  - &phar2

      Name: phar2

      ID: phar2MSP

      MSPDir: crypto-config/peerOrganizations/phar2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('phar2MSP.admin', 'phar2MSP.peer', 'phar2MSP.client', 'phar2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('phar2MSP.admin', 'phar2MSP.client', 'phar2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('phar2MSP.admin', 'phar2MSP.member')"

      AnchorPeers:

        - Host: peer0.phar2.meditrack.com
          Port: 7051

  - &ia1

      Name: ia1

      ID: ia1MSP

      MSPDir: crypto-config/peerOrganizations/ia1.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('ia1MSP.admin', 'ia1MSP.peer', 'ia1MSP.client', 'ia1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ia1MSP.admin', 'ia1MSP.client', 'ia1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ia1MSP.admin', 'ia1MSP.member')"

      AnchorPeers:

        - Host: peer0.ia1.meditrack.com
          Port: 7051

  - &ia2

      Name: ia2

      ID: ia2MSP

      MSPDir: crypto-config/peerOrganizations/ia2.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      Policies:
            Readers:
                Type: Signature
                Rule: "OR('ia2MSP.admin', 'ia2MSP.peer', 'ia2MSP.client', 'ia2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('ia2MSP.admin', 'ia2MSP.client', 'ia2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('ia2MSP.admin', 'ia2MSP.member')"

      AnchorPeers:

        - Host: peer0.ia2.meditrack.com
          Port: 7051

Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer.meditrack.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

  Kafka:
    Brokers:
      - kafka0:9092
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092

  Organizations:

Capabilities:
  Channel: &ChannelCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: false
    V1_1: false

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
    Capabilities:
        <<: *ChannelCapabilities

Application: &ApplicationDefaults

  Organizations:

  Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

Profiles:

  ProfileTest:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ComposerConsortium:
        Organizations:
          - *manu1
          - *manu2
          - *dist1
          - *dist2
          - *logi1
          - *logi2
          - *phar1
          - *phar2
          - *ia1
          - *ia2
      agritrackConsortium:
        Organizations:
          - *manu1
          - *manu2
          - *dist2
          - *logi2
          - *phar2
          - *ia2
      meditrackConsortium:
        Organizations:
          - *manu1
          - *dist1
          - *logi1
          - *phar1
          - *ia1

  ChannelTest:
    <<: *ChannelDefaults
    Consortium: ComposerConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *manu1
          - *manu2
          - *dist1
          - *dist2
          - *logi1
          - *logi2
          - *phar1
          - *phar2
          - *ia1
          - *ia2
      Capabilities:
          <<: *ApplicationCapabilities
  agritrackChannel:
    Consortium: agritrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *manu1
          - *manu2
          - *dist2
          - *logi2
          - *phar2
          - *ia2
      Capabilities:
          <<: *ApplicationCapabilities
    
  meditrackChannel:
    <<: *ChannelDefaults
    Consortium: meditrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *manu1
          - *dist1
          - *logi1
          - *phar1
          - *ia1
      Capabilities:
          <<: *ApplicationCapabilities