Organizations:

  - &OrdererOrg

      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/meditrack.com/msp

      AdminPrincipal: Role.MEMBER


  - &bayer

      Name: bayer

      ID: bayerMSP

      MSPDir: crypto-config/peerOrganizations/bayer.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.bayer.meditrack.com
          Port: 7051
      

  - &aimco

      Name: aimco

      ID: aimcoMSP

      MSPDir: crypto-config/peerOrganizations/aimco.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.aimco.meditrack.com
          Port: 7051

  - &gaia

      Name: gaia

      ID: gaiaMSP

      MSPDir: crypto-config/peerOrganizations/gaia.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.gaia.meditrack.com
          Port: 7051

  - &migrow

      Name: migrow

      ID: migrowMSP

      MSPDir: crypto-config/peerOrganizations/migrow.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.migrow.meditrack.com
          Port: 7051

  - &fedx

      Name: fedx

      ID: fedxMSP

      MSPDir: crypto-config/peerOrganizations/fedx.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.fedx.meditrack.com
          Port: 7051

  - &dtdc

      Name: dtdc

      ID: dtdcMSP

      MSPDir: crypto-config/peerOrganizations/dtdc.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.dtdc.meditrack.com
          Port: 7051

  - &apollo

      Name: apollo

      ID: apolloMSP

      MSPDir: crypto-config/peerOrganizations/apollo.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.apollo.meditrack.com
          Port: 7051

  - &care

      Name: care

      ID: careMSP

      MSPDir: crypto-config/peerOrganizations/care.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.care.meditrack.com
          Port: 7051

  - &cdsco

      Name: cdsco

      ID: cdscoMSP

      MSPDir: crypto-config/peerOrganizations/cdsco.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.cdsco.meditrack.com
          Port: 7051

  - &cibrc

      Name: cibrc

      ID: cibrcMSP

      MSPDir: crypto-config/peerOrganizations/cibrc.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.cibrc.meditrack.com
          Port: 7051

Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer.meditrack.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Kafka:
    Brokers:
      - kafka0:9092
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092

  Organizations:

Capabilities:
  Channel: &ChannelCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: false
    V1_1: false

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins
    Capabilities:
        <<: *ChannelCapabilities

Application: &ApplicationDefaults

  Organizations:

Profiles:

  ProfileTest:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ComposerConsortium:
        Organizations:
          - *bayer
          - *aimco
          - *gaia
          - *migrow
          - *fedx
          - *dtdc
          - *apollo
          - *care
          - *cdsco
          - *cibrc
      agritrackConsortium:
        Organizations:
          - *bayer
          - *aimco
          - *migrow
          - *dtdc
          - *care
          - *cibrc
      meditrackConsortium:
        Organizations:
          - *bayer
          - *gaia
          - *fedx
          - *apollo
          - *cdsco

  ChannelTest:
    <<: *ChannelDefaults
    Consortium: ComposerConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *bayer
          - *aimco
          - *gaia
          - *migrow
          - *fedx
          - *dtdc
          - *apollo
          - *care
          - *cdsco
          - *cibrc
      Capabilities:
          <<: *ApplicationCapabilities
  agritrackChannel:
    Consortium: agritrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *bayer
          - *aimco
          - *migrow
          - *dtdc
          - *care
          - *cibrc
      Capabilities:
          <<: *ApplicationCapabilities
    
  meditrackChannel:
    <<: *ChannelDefaults
    Consortium: meditrackConsortium
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *bayer
          - *gaia
          - *fedx
          - *apollo
          - *cdsco
      Capabilities:
          <<: *ApplicationCapabilities