Organizations:

  - &OrdererOrg

      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/meditrack.com/msp

      AdminPrincipal: Role.MEMBER

  - &cipla

      Name: cipla

      ID: ciplaMSP

      MSPDir: crypto-config/peerOrganizations/cipla.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.cipla.meditrack.com
          Port: 7051

  - &drreddy

      Name: drreddy

      ID: drreddyMSP

      MSPDir: crypto-config/peerOrganizations/drreddy.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.drreddy.meditrack.com
          Port: 7051

  - &dtdc

      Name: dtdc

      ID: dtdcMSP

      MSPDir: crypto-config/peerOrganizations/dtdc.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.dtdc.meditrack.com
          Port: 7051

  - &bluedart

      Name: bluedart

      ID: bluedartMSP

      MSPDir: crypto-config/peerOrganizations/bluedart.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.bluedart.meditrack.com
          Port: 7051

  - &emcure

      Name: emcure

      ID: emcureMSP

      MSPDir: crypto-config/peerOrganizations/emcure.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.emcure.meditrack.com
          Port: 7051

  - &pharmdeal

      Name: pharmdeal

      ID: pharmdealMSP

      MSPDir: crypto-config/peerOrganizations/pharmdeal.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.pharmdeal.meditrack.com
          Port: 7051

  - &apollo

      Name: apollo

      ID: apolloMSP

      MSPDir: crypto-config/peerOrganizations/apollo.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.apollo.meditrack.com
          Port: 7051

  - &medplus

      Name: medplus

      ID: medplusMSP

      MSPDir: crypto-config/peerOrganizations/medplus.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.medplus.meditrack.com
          Port: 7051

Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer.meditrack.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Kafka:
    Brokers:
      - kafka0:9092
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092

  Organizations:

Application: &ApplicationDefaults

  Organizations:

Profiles:

  ProfileTest:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      ComposerConsortium:
        Organizations:
          - *cipla
          - *drreddy
          - *dtdc
          - *bluedart
          - *emcure
          - *pharmdeal
          - *apollo
          - *medplus

  ChannelTest:
    Consortium: ComposerConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *cipla
          - *drreddy
          - *dtdc
          - *bluedart
          - *emcure
          - *pharmdeal
          - *apollo
          - *medplus