OrdererOrgs:

  - Name: Orderer
    Domain: meditrack.com

    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: mayer
    Domain: mayer.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: aimko
    Domain: aimko.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: baia
    Domain: baia.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: bigrow
    Domain: bigrow.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: dedx
    Domain: dedx.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: btdc
    Domain: btdc.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: abollo
    Domain: abollo.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: fare
    Domain: fare.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: cdsco
    Domain: cdsco.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: cibrc
    Domain: cibrc.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3