OrdererOrgs:

  - Name: Orderer
    Domain: meditrack.com

    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: manu1
    Domain: manu1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: manu2
    Domain: manu2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: dist1
    Domain: dist1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: dist2
    Domain: dist2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: logi1
    Domain: logi1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: logi2
    Domain: logi2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: phar1
    Domain: phar1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: phar2
    Domain: phar2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: ia1
    Domain: ia1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: ia2
    Domain: ia2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3