OrdererOrgs:

  - Name: Orderer
    Domain: meditrack.com

    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: manuf1
    Domain: manuf1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: manuf2
    Domain: manuf2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: distr1
    Domain: distr1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: distr2
    Domain: distr2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: logistic1
    Domain: logistic1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: logistic2
    Domain: logistic2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: pharmacy1
    Domain: pharmacy1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: pharmacy2
    Domain: pharmacy2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: ia1
    Domain: ia1.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: ia2
    Domain: ia2.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3