OrdererOrgs:

  - Name: Orderer
    Domain: meditrack.com

    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: bayer
    Domain: bayer.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: aimco
    Domain: aimco.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: gaia
    Domain: gaia.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: migrow
    Domain: migrow.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: fedx
    Domain: fedx.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: dtdc
    Domain: dtdc.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: apollo
    Domain: apollo.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: care
    Domain: care.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: cdsco
    Domain: cdsco.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3

  - Name: cibrc
    Domain: cibrc.meditrack.com

    Template:
      Count: 1

    Users:
      Count: 3