Organizations:

  - &OrdererOrg

      Name: OrdererOrg

      ID: OrdererMSP

      MSPDir: crypto-config/ordererOrganizations/meditrack.com/msp

      AdminPrincipal: Role.MEMBER


  - &manu

      Name: manu

      ID: manuMSP

      MSPDir: crypto-config/peerOrganizations/manu.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.manu.meditrack.com
          Port: 7051

  - &logi

      Name: logi

      ID: logiMSP

      MSPDir: crypto-config/peerOrganizations/logi.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.logi.meditrack.com
          Port: 7051

  - &dist

      Name: dist

      ID: distMSP

      MSPDir: crypto-config/peerOrganizations/dist.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.dist.meditrack.com
          Port: 7051

  - &phar

      Name: phar

      ID: pharMSP

      MSPDir: crypto-config/peerOrganizations/phar.meditrack.com/msp

      AdminPrincipal: Role.MEMBER

      AnchorPeers:

        - Host: peer0.phar.meditrack.com
          Port: 7051

Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer.meditrack.com:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Kafka:
    Brokers:
      - kafka0:9092
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092

  Organizations:

Capabilities:
   # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.
    # Set the value of the capability to true to require it.
  Channel: &ChannelCapabilities
    # V1.3 for Channel is a catchall flag for behavior which has been
    # determined to be desired for all orderers and peers running at the v1.3.x
    # level, but which would be incompatible with orderers and peers from
    # prior releases.
    # Prior to enabling V1.3 channel capabilities, ensure that all
    # orderers and peers on a channel are at v1.3.0 or later.
    V1_3: true
    # Orderer capabilities apply only to the orderers, and may be safely
    # used with prior release peers.
    # Set the value of the capability to true to require it.
  Orderer: &OrdererCapabilities
    # V1.1 for Orderer is a catchall flag for behavior which has been
    # determined to be desired for all orderers running at the v1.1.x
    # level, but which would be incompatible with orderers from prior releases.
    # Prior to enabling V1.1 orderer capabilities, ensure that all
    # orderers on a channel are at v1.1.0 or later.
    V1_1: true
  Application: &ApplicationCapabilities
    # V1.3 for Application enables the new non-backwards compatible
    # features and fixes of fabric v1.3.
    V1_3: true
    # V1.2 for Application enables the new non-backwards compatible
    # features and fixes of fabric v1.2 (note, this need not be set if
    # later version capabilities are set)
    V1_2: false
    # V1.1 for Application enables the new non-backwards compatible
    # features and fixes of fabric v1.1 (note, this need not be set if
    # later version capabilities are set).
    V1_1: false

Application: &ApplicationDefaults

  Organizations:

Profiles:

  ProfileTest:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      ComposerConsortium:
        Organizations:
          - *manu
          - *logi
          - *dist
          - *phar

  ChannelTest:
    Consortium: ComposerConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
          - *manu
          - *logi
          - *dist
          - *phar
      Capabilities:
          <<: *ApplicationCapabilities