version: '2'

networks:
  meditrack:

services:

  orderer.meditrack.com:
    container_name: orderer.meditrack.com
    image: hyperledger/fabric-orderer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    environment:
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ../chaincode:/etc/hyperledger/chaincode
      - ./crypto-config/ordererOrganizations/meditrack.com/orderers/orderer.meditrack.com/msp:/etc/hyperledger/msp/orderer/msp
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - meditrack

  kafka0:
    container_name: kafka0
    extends:
        file: docker-compose-base.yml
        service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=103809024
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - meditrack

  kafka1:
    container_name: kafka1
    extends:
        file: docker-compose-base.yml
        service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=103809024
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - meditrack

  kafka2:
    container_name: kafka2
    extends:
        file: docker-compose-base.yml
        service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=103809024
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - meditrack

  kafka3:
    container_name: kafka3
    extends:
        file: docker-compose-base.yml
        service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=103809024
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      - meditrack

  zookeeper0:
    container_name: zookeeper0
    extends:
        file: docker-compose-base.yml
        service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - meditrack

  zookeeper1:
    container_name: zookeeper1
    extends:
        file: docker-compose-base.yml
        service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - meditrack

  zookeeper2:
    container_name: zookeeper2
    extends:
        file: docker-compose-base.yml
        service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - meditrack

  ca.manu.meditrack.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.manu.meditrack.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manu.meditrack.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/eb0bc5116d33e9b31d3d01c9337bc96037bda0c622c3bb1fe10485d20c5ef489_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.manu.meditrack.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/*_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/manu.meditrack.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.manu.meditrack.com
    networks:
      - meditrack

  peer0.manu.meditrack.com:
    container_name: peer0.manu.meditrack.com
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    environment:
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.manu.meditrack.com
      - CORE_PEER_ADDRESS=peer0.manu.meditrack.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_meditrack
      - CORE_PEER_LOCALMSPID=manuMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manu.meditrack.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ../chaincode:/etc/hyperledger/chaincode
      - ./crypto-config/peerOrganizations/manu.meditrack.com/peers/peer0.manu.meditrack.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/manu.meditrack.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.meditrack.com
      - couchdb0
    networks:
      - meditrack

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:latest
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
    networks:
      - meditrack

  ca.logi.meditrack.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.logi.meditrack.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.logi.meditrack.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a85a9dde3f192f6775ed263a2ff5d7b6c7c7470c524d41bb79d0924477d66a47_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.logi.meditrack.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/*_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/logi.meditrack.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.logi.meditrack.com
    networks:
      - meditrack

  peer0.logi.meditrack.com:
    container_name: peer0.logi.meditrack.com
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    environment:
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.logi.meditrack.com
      - CORE_PEER_ADDRESS=peer0.logi.meditrack.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_meditrack
      - CORE_PEER_LOCALMSPID=logiMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.logi.meditrack.com:8051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ../chaincode:/etc/hyperledger/chaincode
      - ./crypto-config/peerOrganizations/logi.meditrack.com/peers/peer0.logi.meditrack.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/logi.meditrack.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.meditrack.com
      - couchdb1
    networks:
      - meditrack

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:latest
    ports:
      - 6984:5984
    environment:
      DB_URL: http://localhost:6984/member_db
    networks:
      - meditrack

  ca.dist.meditrack.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.dist.meditrack.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dist.meditrack.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f9d540337b7766ede53b02cb932e72e2dd9849c10eb92b1cf8474d21e70c347b_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dist.meditrack.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/*_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/dist.meditrack.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.dist.meditrack.com
    networks:
      - meditrack

  peer0.dist.meditrack.com:
    container_name: peer0.dist.meditrack.com
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    environment:
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.dist.meditrack.com
      - CORE_PEER_ADDRESS=peer0.dist.meditrack.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_meditrack
      - CORE_PEER_LOCALMSPID=distMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dist.meditrack.com:9051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ../chaincode:/etc/hyperledger/chaincode
      - ./crypto-config/peerOrganizations/dist.meditrack.com/peers/peer0.dist.meditrack.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/dist.meditrack.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.meditrack.com
      - couchdb2
    networks:
      - meditrack

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:latest
    ports:
      - 7984:5984
    environment:
      DB_URL: http://localhost:7984/member_db
    networks:
      - meditrack

  ca.phar.meditrack.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.phar.meditrack.com
      # - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.phar.meditrack.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42162406e175cb9637b0c8fecc54537ce796f34108b8ab9140768b7215d2459c_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.phar.meditrack.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/*_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/phar.meditrack.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.phar.meditrack.com
    networks:
      - meditrack

  peer0.phar.meditrack.com:
    container_name: peer0.phar.meditrack.com
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    environment:
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.phar.meditrack.com
      - CORE_PEER_ADDRESS=peer0.phar.meditrack.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_meditrack
      - CORE_PEER_LOCALMSPID=pharMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.phar.meditrack.com:10051
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ../chaincode:/etc/hyperledger/chaincode
      - ./crypto-config/peerOrganizations/phar.meditrack.com/peers/peer0.phar.meditrack.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/phar.meditrack.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.meditrack.com
      - couchdb3
    networks:
      - meditrack

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:latest
    ports:
      - 8984:5984
    environment:
      DB_URL: http://localhost:8984/member_db
    networks:
      - meditrack