################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org1
            # DefaultOrg defines the organization which is used in the sampleconfig
            # of the fabric.git development environment
        Name: m-OUELIBUUXBGFJA3CKI5JE437PM
            # ID to load the MSP definition as
        ID: m-OUELIBUUXBGFJA3CKI5JE437PM
        MSPDir: /opt/home/admin-msp
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
        AnchorPeers: 
            - Host: nd-rernbicxujh5tcw5poivnfm3zq.m-ouelibuuxbgfja3cki5je437pm.n-mpl3ejibsfgi3d2sbonw2a6cfu.managedblockchain.us-east-1.amazonaws.com
              Port: 30003
        
    - &Org2
            # DefaultOrg defines the organization which is used in the sampleconfig
            # of the fabric.git development environment
        Name: m-X3Z64F6RHRAD7C534DW3DMIBHY
            # ID to load the MSP definition as
        ID: m-X3Z64F6RHRAD7C534DW3DMIBHY
        MSPDir: /opt/home/dist-admin-msp
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
        AnchorPeers:
            - Host: nd-dvyusdsxtjgcfbt2bebbtdo7ay.m-x3z64f6rhrad7c534dw3dmibhy.n-mpl3ejibsfgi3d2sbonw2a6cfu.managedblockchain.us-east-1.amazonaws.com
              Port: 30006

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults
        # Organizations is the list of orgs which are defined as participants on
        # the application side of the network
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:
    TwoOrgChannel:
        Consortium: AWSSystemConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2